### ISSUE TITLE
Add consumer-version-selector to CLI

### ISSUE THREAD

**Issue by alecgerona** [pact-foundation/pact-python#166]
Due to working with the intricacies of Gitlab CI's docker executor, I want to move from using pact-cli to pact-python's `pact-verifier` since my base image is Python anyway. Checking my scripts and I see that `consumer-version-selector` is not yet supported. 

Willing to do a PR for this if needed.

**Comment by mefellows** [comment]
Thanks @alecgerona - yes a PR would be great, thanks!

**Comment by elliottmurray** [comment]
I've actually not used consumer-version-selector - is that actually an option on the ruby cli? I can't see it. It's pretty easy to expose via Click/python and can get it done typically in an hour or 2. And should be able to add it to the python Verifier class if you prefer that method too. So I'm on UK time - if you want to have a crack go ahead or give me an example and I'll do it tomorrow.

And a Django example would be great. I have almost got a simple e2e that I wanted to extend to publishing results for but got stuck on a not too dissimilar problem in travis around connecting to my provider that I still haven't resolved (and probably should look at it again!) 

And instead of using sleep I've been playing with the retry strategy (if in Python code)

**Comment by alecgerona** [comment]
@elliottmurray yup. Calling `verify help` using `pact-cli` should show the `--consumer-version-selector` flag. Apparently according to the docs this is more preferred than using tags. Will make a PR tomorrow.
