### ISSUE TITLE
Examples code contains provider verifications that does not publish results to broker

### ISSUE THREAD

**Issue by neringaalt** [pact-foundation/pact-python#445]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/pact-foundation/pact-python/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of `pact-python`.
- [x] I have read the console error message carefully (if applicable).

### Description

It is a super easy to fix bug, but I was not able to open PR for this:
Examples code contains `published_verification_results` instead of `publish_verification_results`

### Steps to reproduce

I am running examples using poetry run pytest test_01_provider_fastapi.py -s   

### Expected behavior

Provider verification should be publish to the broker.

### Actual behavior

Provider verification tests are passing, but results are not publish and have status pending. 

### Your environment

Poetry 1.6.1
Python 3.11
pact-python 2.0.1

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by JP-Ellis** [comment]
Thanks for the bug report!

Is the bug just the typo? I'd be happy to help you make the PR, because you _should_ be able to create one which requires creating a fork first. You then make the modifications in the fork and create the PR pulling changes from your fork into this repo.

Let me know how you go, and feel free to reach out if you have any other questions!

**Comment by neringaalt** [comment]
PR for this https://github.com/pact-foundation/pact-python/pull/455
