### ISSUE TITLE
Feature request: publishing pacts to a Pact broker

### ISSUE THREAD

**Issue by nikroth** [pact-foundation/pact-python#99]
I am having difficulty figuring out how to publish python pacts to the pact broker.  My broker is set up and I've been able to successfully publish Java and Clojure pacts to it.  I have found a fair amount of documentation and examples for _verifying_ with pact-python, and I have also found indications that it's _possible_ to publish python pacts to a pact broker, but I cannot for the life of me find any documentation about _how_ to do this.  I must be missing something.  Any help would be appreciated.

**Comment by mefellows** [comment]
Take a look at the link that @zom-pro sent. It would be nice if the other (e.g. publishing) tools from https://github.com/pact-foundation/pact-ruby-standalone/releases were exposed via an interface here as they are in some of the other languages.

That being said, you can just pull them down your self and run them (in fact, they _will_ be made availaable on your system somewhere, not sure where pip/python will put them but they are used by the library under the hood).

**Comment by maxg203** [comment]
I second the difficulties experienced by @nikroth. Looking at the `Consumer`/`Pact` class implementations, I think it would make sense to add an additional parameter like `broker_url`, also possibly `broker_username` and `broker_password` for optional basic auth as other packages have done (e.g. [this pact-js one](https://github.com/pact-foundation/pact-js#publishing-options)).

Only the `broker_url` would be required, and if it is specified logically I would expect that we'd make a the relevant PUT request ([as documented here](https://github.com/pact-foundation/pact_broker/wiki/Publishing-and-retrieving-pacts)) instead of writing the json to disk.

@zom-pro would you like to implement this? If not I might have a go.

**Comment by mefellows** [comment]
@maxg203 there is nothing magical about publishing pacts to the broker. The CLI utility referenced above will do this for you, which is usually easily achieved with a few lines of bash/PoSH/<insert scripting language>.

That being said, we'd happily also see this integrated into the python DSL and if you were interested in submitting a PR we'd be grateful.

The JS code you referenced is really just a simple wrapper over that utility, so you could use that as a guide.

**Comment by m-aciek** [comment]
I think the issue can be closed now. You can publish pacts using pact-python.
